version: 2.1
orbs:
  ruby: circleci/ruby@1.0.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps:
          with-cache: true
      - ruby/rspec-test
