version: 2.1
orbs:
  ruby: circleci/ruby@1.0.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps:
          with-cache: true
      - run:
          name: use the dummy
          command: cd test/dummy
      - run:
          name: load the schema
          command: bundle exec rails db:schema:load --trace
      - run:
          name: test the thing
          command: bundle exec rspec

workflows:
  build_test:
    jobs:
      - build
