version: 2.1
orbs:
  ruby: circleci/ruby@1.0.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - restore-cache
          key: kasey-26-{{ checksum "Gemfile.lock" }}
      - ruby/install-deps:
          with-cache: false

      # Bundle install dependencies
      #- run: bundle install --path vendor/bundle

      - save-cache
          key: kasey-26-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: load the schema
          working_directory: ~/project/test/dummy
          command: bundle exec rails db:schema:load --trace
      - run:
          name: test the thing
          working_directory: ~/project/test/dummy
          command: bundle exec rspec

workflows:
  build_test:
    jobs:
      - build
